FROM payaradocker/j1-payara-micro
MAINTAINER Toshiaki Maki <makingx at gmail.com>

RUN wget http://repository.primefaces.org/org/primefaces/showcase/5.2/showcase-5.2.war -O /opt/payara-micro-wars/showcase-5.2.war

EXPOSE 8080

